---
title: "Onet"
author: "simplymathematics"
date: "October 19, 2018"
output: html_document
---

# Dependencies

```{r}
require(XML) #for reading xml, html
require(stringr) #for regex
require(curl)
require(tidyr)
```

# Downloading
We will use the onet database to generate our list of skills.

```{r}
curl_download("https://www.onetcenter.org/dl_files/database/db_23_0_text/Skills.txt", "Skills.txt")
```
# Reading File
The code below reads the data and discards all of the non mathematics fields.
```{r}
df<- read.table("Skills.txt", sep = '\t', header = TRUE)
df <- df[grep("15-", df$O.NET.SOC.Code),]
```
# Cleaning Data
```{r}
df$O.NET.SOC.Code <- substr(x = df$O.NET.SOC.Code, 4, 7) #drops sub occupation data
df <- df[grep("IM", df$Scale.ID),] # only cares about importance data
unique(df$Element.Name)
df

```
```{r}
skills <- unique(df$Element.Name)
names <- unique(df$O.NET.SOC.Code)
print("************")
df$Element.Name
## TO DO MATch skills with list
small.data <- data.frame(c(df$O.NET.SOC.Code, df$Element.Name), ncol=2)
small.data <- data.frame(small.data)
colnames(small.data) <- c("Code", "Skill")
small.data
#test <- spread(small.data, key = "Code", value = "Skill")
#test
```
```{r}
ncols <- length(skills) +1
nrows <- length(names)
ncols
nrows
```

```{r}
new.frame <- data.frame(matrix(ncol=ncols, nrow=nrows))
skills
col.names <- c("Jobs", c(skills))
colnames(new.frame) <- col.names
new.frame

for (row in nrows){
  for (col in ncols){
    if (df[df$O.Net.SOC.Code == name & df$Element.Name == skill]){
      new.frame[col][row] = TRUE
    }
    else{
        new.frame[col][row] = FALSE
    }
  }
}
```

```{r}

```